<?php

namespace Database\Seeders;

use App\Models\Members;
use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        Members::upsert([
            [
                'member_id' => 1,
                'member_fname' => 'Andy Andrade II',
                'member_mname' => 'A',
                'member_lname' => 'Mina',
                'gender' => 'Male',
                'birth_date' => '2005-04-12',
                'email' => 'mina@gmail.com',
                'phone_number' => '0123456789',
                'province' => 'Davao Del Sur',
                'city' => 'Davao',
                'street' => 'Matina',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'member_id' => 2,
                'member_fname' => 'Claudee',
                'member_mname' => 'A',
                'member_lname' => 'Galon',
                'gender' => 'Male',
                'birth_date' => '2005-04-01',
                'email' => 'claudee@gmail.com',
                'phone_number' => '0912387654',
                'province' => 'Davao Del Sur',
                'city' => 'Davao',
                'street' => 'Mandug',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'member_id' => 3,
                'member_fname' => 'Geoff Patrick',
                'member_mname' => 'G',
                'member_lname' => 'Granada',
                'gender' => 'Male',
                'birth_date' => '2005-05-04',
                'email' => 'Granada@gmail.com',
                'phone_number' => '987654321',
                'province' => 'Davao del sur',
                'city' => 'Matina',
                'street' => 'Grenade',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'member_id' => 4,
                'member_fname' => 'Joen',
                'member_mname' => 'R',
                'member_lname' => 'Reloba',
                'gender' => 'Male',
                'birth_date' => '2005-09-27',
                'email' => 'Reloba@gmail.com',
                'phone_number' => '214365879',
                'province' => 'Davao del sur',
                'city' => 'Toril',
                'street' => 'Jomaine',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'member_id' => 5,
                'member_fname' => 'Jhonn Crisler',
                'member_mname' => 'L',
                'member_lname' => 'Lazar',
                'gender' => 'Male',
                'birth_date' => '2000-03-14',
                'email' => 'Lazar@gmail.com',
                'phone_number' => '543216789',
                'province' => 'Davao del sur',
                'city' => 'Gravahan',
                'street' => 'Traydor',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'member_id' => 6,
                'member_fname' => 'Geonathan Niel',
                'member_mname' => 'P',
                'member_lname' => 'Penafiel',
                'gender' => 'Male',
                'birth_date' => '2006-06-01',
                'email' => 'Geonathan@gmail.com',
                'phone_number' => '786591234',
                'province' => 'Davao del sur',
                'city' => 'Wala ko Balo',
                'street' => 'Armlet God',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'member_id' => 7,
                'member_fname' => 'Francis Laurence',
                'member_mname' => 'C',
                'member_lname' => 'Calla',
                'gender' => 'Male',
                'birth_date' => '2004-02-21',
                'email' => 'Calla@gmail.com',
                'phone_number' => '918273645',
                'province' => 'Davao del sur',
                'city' => 'Pastil',
                'street' => 'Barato',
                'is_archived' => false,
                'archived_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['member_id'], [
            'member_fname',
            'member_mname',
            'member_lname',
            'gender',
            'birth_date',
            'email',
            'phone_number',
            'province',
            'city',
            'street',
            'is_archived',
            'archived_at',
            'updated_at',
        ]);
    }
}
